### ISSUE TITLE
App does not go to cognitive exercises 

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/CALM#10]
Ver 0.0.3

After a 4-minute-paced baseline, the app does not continue to cognitive exercises (I did not quit the app. The only screen that appears is a black loading bar after pressing the button to continue). I attached photos from the console, application, and network tab.

![IMG_2493](https://github.com/user-attachments/assets/a87ee4d7-ee84-4abd-864e-4b12350af43b)
![IMG_2495](https://github.com/user-attachments/assets/c9ddb3a5-2c62-4cf6-ad3a-d8fc24a48bca)
![IMG_2494](https://github.com/user-attachments/assets/1732e054-0f1b-4889-b95f-2dd03d805125)

**Comment by noah10** [comment]
This should be fixed in version 0.0.4.

**Comment by choipaul92** [comment]
Ver 0.0.5 

After the baseline breathing practices, the cognitive assessments are now accessible
