### ISSUE TITLE
Stage 2 day reset

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/CALM#22]
If the participant does not do all their 2-min rests in a day, they should not be asked to do them the next day - it should start with Lumosity the next day. It should work to follow the stage 3 procedure for the day boundaries.

**Comment by maramather** [comment]
I have edited the app spec as requested

**Comment by noah10** [comment]
This is addressed in v0.0.7.

**Comment by nashiro** [comment]
fixed
