### ISSUE TITLE
Cannot move forward with the next set of paced breathing in Stage 1

### ISSUE THREAD

**Issue by juliana-20** [EmotionCognitionLab/CALM#7]
During 4-mins of paced breathing right after resting pulse at baseline, the countdown works (4 mins remaining, then 3 mins remaining, and so forth). At the end, the start button is still faded out and the app doesn't proceed with the new instructions for the next paced breathing exercises. 

![image](https://github.com/user-attachments/assets/60df546f-9e53-49db-a9ab-4260e4573973)

**Comment by noah10** [comment]
I'm unable to reproduce this. I think that my fix for #6 might have fixed this as well. In order to test it again I'll need to delete some of your data - let me know when you're ready for me to do that.

**Comment by choipaul92** [comment]
Ver 0.0.3

I was able to proceed to the next stage into the four-minute paced breathing 
[Stage1_first_4min.pdf](https://github.com/user-attachments/files/18158456/Stage1_first_4min.pdf)

**Comment by juliana-20** [comment]
Fixed
