### ISSUE TITLE
Audio Pacer Does Not Work: Stage 1 for 4 minute Paced Baseline

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/CALM#8]
Dev Ver 0.0.3

The audio pacer during Stage 1 does not work for all 4 minute paced baselines.

**Comment by noah10** [comment]
This should be fixed in version 0.0.4.

**Comment by juliana-20** [comment]
Version 0.0.5 - audio for paced breathing works

**Comment by choipaul92** [comment]
Ver 0.0.5 - audio pacing for breathing works
