### ISSUE TITLE
Quitting right before doing cognitive exercises skips them

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/CALM#9]
If you quit (or the app crashes) when you are on the screen that says "Great! You're finished with the breathing exercises. Next up: some cognitive exercises" then you will never do the cognitive exercises.

**Comment by choipaul92** [comment]
Ver 0.0.3

Update: After a 4-minute-paced baseline, the app does not continue to cognitive exercises (I did not quit the app. The only screen that appears is a black loading bar after pressing the button to continue). I attached photos from the console, application, and network tab. 

![IMG_2495](https://github.com/user-attachments/assets/754f5beb-2fe4-4e28-91a7-42969940cb2a)
![IMG_2494](https://github.com/user-attachments/assets/7b33b85a-544c-4f47-ad6e-60357bea555c)
![IMG_2493](https://github.com/user-attachments/assets/e6086e62-71b0-47dc-b523-a2da8b40acfb)

**Comment by noah10** [comment]
This is fixed in version 0.0.4.
